spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: false
  h2:
    console:
      enabled: true
  flyway:
    locations=filesystem:db/migration:

logging:
  level:
    root: INFO