apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixaris-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ixaris-app
          env:
          - name: NEW_RELIC_LABELS
            value: Platform:aws;Environment:dev;Jurisdiction:com;Product:scoreboards;Component:launcher;Owner:sbit;Channel:sports


